#!/usr/bin/env python3
"""
Pass 1 Section 2: Extract claims, evidence, and implicit arguments
from Methodology chunk 1 (sections 2, 2.1, 2.2, pages 2-5)

Liberal extraction philosophy: When uncertain, include it.
Mandatory sourcing: All explicit items require verbatim_quote.
All implicit arguments require trigger_text + trigger_locations + inference_reasoning.
"""

import json
from datetime import datetime, timezone
from pathlib import Path

# Load current extraction
extraction_file = Path("extraction.json")
with open(extraction_file) as f:
    data = json.load(f)

print("Extracting evidence from Methodology chunk 1...")

# New EVIDENCE items (E011-E025)
new_evidence = [
    {
        "evidence_id": "E011",
        "evidence_text": "GPS location, dimensions, surrounding land-use, and condition of 773 burial mounds collected by trained personnel using standardised record sheets during 2009-2011 survey campaigns",
        "evidence_type": "dataset_description",
        "evidence_basis": "observational_record",
        "supports_claims": ["C039"],
        "location": {
            "section": "2.1. Dataset",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "TRAP compiled the burial mound dataset during three archaeological surface survey campaigns in the Kazanlak Valley during 2009–2011 (Ross et al. forthcoming). GPS location, dimensions, surrounding land-use, and condition of 773 burial mounds were collected by trained personnel using standardised record sheets over the course of regional, total-coverage, pedestrian survey",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E012",
        "evidence_text": "Elevations extracted from ASTER digital elevation model",
        "evidence_type": "data_source",
        "evidence_basis": "derived_calculation",
        "supports_claims": [],
        "location": {
            "section": "2.1. Dataset",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "Elevations were extracted from an ASTER digital elevation model.",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E013",
        "evidence_text": "Distance to nearest urban boundary calculated using Distance Matrix plugin in qGIS on boundary polygons generated by JICA in 1994",
        "evidence_type": "derived_measurement",
        "evidence_basis": "derived_calculation",
        "supports_claims": [],
        "location": {
            "section": "2.1. Dataset",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "The distance to the nearest urban boundary was calculated using the Distance Matrix plugin in qGIS on the boundary polygons generated by the Japanese International Cooperation Agency (JICA) in 1994.",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E014",
        "evidence_text": "Mounds most frequent in pasture: 70.4% of mounds in 23.5% of survey area (2020 ha)",
        "evidence_type": "quantitative_observation",
        "evidence_basis": "statistical_output",
        "supports_claims": ["C041"],
        "location": {
            "section": "2.2. Variables",
            "page": 3,
            "start_paragraph": 3,
            "end_paragraph": 3
        },
        "verbatim_quote": "Mounds were most frequent in pasture, which comprised only 23.5% of the survey area (2020 ha), but contained 70.4% of the mounds (544).",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E015",
        "evidence_text": "Annual agriculture comprised 53.1% of survey area (4564 ha) but contained only 13.5% of mounds (104)",
        "evidence_type": "quantitative_observation",
        "evidence_basis": "statistical_output",
        "supports_claims": ["C041"],
        "location": {
            "section": "2.2. Variables",
            "page": 3,
            "start_paragraph": 3,
            "end_paragraph": 3
        },
        "verbatim_quote": "Conversely, annual agricultural ﬁelds comprised 53.1% of the area (4564 ha), but contained only 13.5% of the mounds (104).",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E016",
        "evidence_text": "Density of mounds per sq km: 26.9 in pasture vs 2.3 in annual agriculture",
        "evidence_type": "quantitative_measurement",
        "evidence_basis": "statistical_output",
        "supports_claims": ["C041"],
        "location": {
            "section": "2.2. Variables",
            "page": 3,
            "start_paragraph": 3,
            "end_paragraph": 3
        },
        "verbatim_quote": "Put another way, the density of mounds per sq km was high in pasture, but low in annual agriculture (26.9 vs 2.3 respectively).",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E017",
        "evidence_text": "Mean distance to nearest urban boundary was 936 m with most mounds lying within about 1800 m of a town",
        "evidence_type": "quantitative_measurement",
        "evidence_basis": "statistical_output",
        "supports_claims": [],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "Distance to the nearest urban boundary is a continuous variable; mean distance was 936 m, with most mounds lying within about 1800 m of a town",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E018",
        "evidence_text": "Standard deviation of distance to nearest urban boundary is 673 m",
        "evidence_type": "quantitative_measurement",
        "evidence_basis": "statistical_output",
        "supports_claims": [],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "We used the standard deviation of this distance (673 m) as the projected change for simulations.",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E019",
        "evidence_text": "Mound height ranges from 0 (extinct mounds) to 20 m with mean 1.7 m and median 0.8 m",
        "evidence_type": "quantitative_measurement",
        "evidence_basis": "statistical_output",
        "supports_claims": [],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 3,
            "end_paragraph": 3
        },
        "verbatim_quote": "It is a continuous variable, ranging from 0 (extinct mounds detectable by soil marks or other traces) to 20 m. Smaller mounds predominate (Fig. 5C), with a mean height of 1.7 m but a median of only 0.8 m.",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E020",
        "evidence_text": "Category 2 mounds (moderate damage) were most numerous at time of survey",
        "evidence_type": "observational_record",
        "evidence_basis": "observational_record",
        "supports_claims": [],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 5,
            "end_paragraph": 5
        },
        "verbatim_quote": "At the time of survey, Category 2 mounds were the most numerous (Fig. 6).",
        "extraction_confidence": "high"
    },
    {
        "evidence_id": "E021",
        "evidence_text": "Preliminary logit simulation comparing distance to nearest urban boundary vs distance to Kazanlak indicated former had much greater impact on mound condition",
        "evidence_type": "analytical_result",
        "evidence_basis": "statistical_output",
        "supports_claims": ["C040"],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "Distance to the nearest urban boundary was selected for modelling instead of distance to Kazanlak after a preliminary logit simulation comparing the two indicated that changes to the former had a much greater impact on mound condition.",
        "extraction_confidence": "high"
    }
]

print(f"  Adding {len(new_evidence)} new evidence items (E011-E021)")

print("Extracting claims from Methodology chunk 1...")

# New CLAIMS items (C031-C055)
new_claims = [
    {
        "claim_id": "C031",
        "claim_text": "Ordered logit model is appropriate for determining vulnerability of burial mounds to anthropogenic threats in Kazanlak Valley",
        "claim_type": "methodological_argument",
        "claim_role": "core",
        "primary_function": "methodological_justification",
        "claim_nature": "evaluative",
        "supported_by": [],
        "supports_claims": ["C001"],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 2,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "We applied an ordered logit model to determine the vulnerability of burial mounds to anthropogenic threats in the Kazanlak Valley.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C032",
        "claim_text": "Researchers in the field believed that looting, agricultural activity, and peri-urban development were the principal factors contributing to ubiquitous mound degradation",
        "claim_type": "interpretation",
        "claim_role": "supporting",
        "primary_function": "empirical_pattern",
        "claim_nature": "descriptive",
        "supported_by": [],
        "supports_claims": [],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "Researchers in the ﬁeld (including the authors) believed that looting, agricultural activity, and peri-urban development were the principal factors contributing to the ubiquitous degradation of the mounds we saw during archaeological survey.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C033",
        "claim_text": "Choosing factors based on field researchers' beliefs constituted a 'perceptive' initial risk assessment",
        "claim_type": "methodological_argument",
        "claim_role": "intermediate",
        "primary_function": "methodological_justification",
        "claim_nature": "evaluative",
        "supported_by": [],
        "supports_claims": ["C032"],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "Choosing these factors over others constituted a 'perceptive' initial risk assessment",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C034",
        "claim_text": "Ploughing, harrowing, and removal of obstacles from fields associated with annual agriculture damage mounds (Hypothesis 1)",
        "claim_type": "theoretical",
        "claim_role": "core",
        "primary_function": "causal_explanation",
        "claim_nature": "causal",
        "supported_by": [],
        "supports_claims": [],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "the ploughing, harrowing, and removal of obstacles from ﬁelds associated with annual agriculture damage mounds",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C035",
        "claim_text": "Conversion of any other land-use type to annual agriculture would tend to damage mounds (Hypothesis 1 prediction)",
        "claim_type": "theoretical",
        "claim_role": "core",
        "primary_function": "predictive",
        "claim_nature": "predictive",
        "supported_by": [],
        "supports_claims": ["C034"],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "so conversion of any other land-use type to annual agriculture would tend to damage mounds",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C036",
        "claim_text": "Proximity to a city, town, or village would contribute to damage as proxy for destructive peri-urban activities like construction and casual looting (Hypothesis 2)",
        "claim_type": "theoretical",
        "claim_role": "core",
        "primary_function": "causal_explanation",
        "claim_nature": "causal",
        "supported_by": [],
        "supports_claims": [],
        "implicit_assumptions": ["IA005"],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "proximity to a city, town, or village would contribute to damage, since it is a proxy for destructive peri-urban activities like construction and casual looting",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C037",
        "claim_text": "Looters would preferentially target larger mounds since they typically contain richer burials than small ones (Hypothesis 3)",
        "claim_type": "theoretical",
        "claim_role": "core",
        "primary_function": "causal_explanation",
        "claim_nature": "causal",
        "supported_by": [],
        "supports_claims": [],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "looters would preferentially target larger mounds, since they typically contain richer burials than small ones.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C038",
        "claim_text": "Small mounds more susceptible to agricultural damage, but damage to large mounds from looting would prove more significant (Hypothesis 3 qualification)",
        "claim_type": "theoretical",
        "claim_role": "intermediate",
        "primary_function": "comparative_assessment",
        "claim_nature": "comparative",
        "supported_by": [],
        "supports_claims": ["C037"],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "We conceded that small mounds are more susceptible to agricultural damage, but thought that damage to large mounds from looting would prove more signiﬁcant",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C039",
        "claim_text": "Analysis uses large number of observations to model relationships between mound condition and predictor variables, testing subjective perceptions of risk",
        "claim_type": "methodological_argument",
        "claim_role": "core",
        "primary_function": "methodological_justification",
        "claim_nature": "evaluative",
        "supported_by": ["E011"],
        "supports_claims": ["C031"],
        "implicit_assumptions": [],
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "The analysis performed here tests our subjective perceptions of risk. We use a large number of observations to model relationships between mound condition and elevation, mound size, surrounding land use (including annual agriculture, perennial agriculture, pasture, or forest), and distance to the nearest urban boundary.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C040",
        "claim_text": "Distance to nearest urban boundary had much greater impact on mound condition than distance to Kazanlak",
        "claim_type": "empirical",
        "claim_role": "intermediate",
        "primary_function": "comparative_assessment",
        "claim_nature": "comparative",
        "supported_by": ["E021"],
        "supports_claims": [],
        "implicit_assumptions": [],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "Distance to the nearest urban boundary was selected for modelling instead of distance to Kazanlak after a preliminary logit simulation comparing the two indicated that changes to the former had a much greater impact on mound condition.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C041",
        "claim_text": "Any change from pasture to annual agriculture may affect a large number of mounds",
        "claim_type": "interpretation",
        "claim_role": "intermediate",
        "primary_function": "predictive",
        "claim_nature": "predictive",
        "supported_by": ["E014", "E015", "E016"],
        "supports_claims": [],
        "implicit_assumptions": [],
        "location": {
            "section": "2.2. Variables",
            "page": 3,
            "start_paragraph": 3,
            "end_paragraph": 3
        },
        "verbatim_quote": "Any change from pasture to annual agriculture, therefore, may affect a large number of mounds.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C042",
        "claim_text": "Ordered logit model provides better theoretical and empirical fit than simple linear regression for observational data with categorical response variables",
        "claim_type": "methodological_argument",
        "claim_role": "core",
        "primary_function": "methodological_justification",
        "claim_nature": "comparative",
        "supported_by": [],
        "supports_claims": ["C031"],
        "implicit_assumptions": [],
        "location": {
            "section": "2.3. Statistical method",
            "page": 4,
            "start_paragraph": 1,
            "end_paragraph": 1
        },
        "verbatim_quote": "An ordered logit model provided the best theoretical and empirical ﬁt for our observational data and desired outcome, predicting shifts in mound condition when explanatory variables changed.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C043",
        "claim_text": "Logit model superior to simple linear regression for accommodating categorical response variables like mound condition",
        "claim_type": "methodological_argument",
        "claim_role": "intermediate",
        "primary_function": "methodological_justification",
        "claim_nature": "comparative",
        "supported_by": [],
        "supports_claims": ["C042"],
        "implicit_assumptions": [],
        "location": {
            "section": "2.3. Statistical method",
            "page": 4,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "We chose a logit response model over a simple linear regression for its superior ability to accommodate categorical response variables like mound condition.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C044",
        "claim_text": "Mound condition (1-5 Likert scale) is best seen as categorical since it represents estimate based on visual inspection with limited precision and consistency",
        "claim_type": "methodological_argument",
        "claim_role": "intermediate",
        "primary_function": "methodological_justification",
        "claim_nature": "evaluative",
        "supported_by": [],
        "supports_claims": ["C043"],
        "implicit_assumptions": [],
        "location": {
            "section": "2.3. Statistical method",
            "page": 4,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "The 1–5 value in the Likert scale indicating mound condition is best seen as categorical, since it represents an estimate based on visual inspection, and even trained personnel can only gauge condition with limited precision and consistency.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C045",
        "claim_text": "Treating condition as continuous variable would imply false precision",
        "claim_type": "methodological_argument",
        "claim_role": "supporting",
        "primary_function": "methodological_justification",
        "claim_nature": "evaluative",
        "supported_by": [],
        "supports_claims": ["C044"],
        "implicit_assumptions": [],
        "location": {
            "section": "2.3. Statistical method",
            "page": 4,
            "start_paragraph": 2,
            "end_paragraph": 2
        },
        "verbatim_quote": "Treating condition as a continuous variable (e.g., from 1 to 100) would imply false precision.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C046",
        "claim_text": "Mound condition is based on subjective observation informed by Wildesen's (1982) concept of 'effect' representing professional judgment about measurable characteristic relating to archaeological value",
        "claim_type": "methodological_argument",
        "claim_role": "supporting",
        "primary_function": "methodological_justification",
        "claim_nature": "descriptive",
        "supported_by": [],
        "supports_claims": [],
        "implicit_assumptions": [],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 5,
            "end_paragraph": 5
        },
        "verbatim_quote": "Mound condition, our response variable, is based on subjective observation of burial mound condition at the time of survey. This variable was informed by Wildesen's (1982, 54) concept of 'effect', which denotes professional judgement about a measurable characteristic relating to the archaeological value of the site.",
        "extraction_confidence": "high"
    },
    {
        "claim_id": "C047",
        "claim_text": "Condition measure collapsed the impact of licit and illicit, intentional and inadvertent activities including infrastructure construction, aggressive ploughing, and looting",
        "claim_type": "methodological_argument",
        "claim_role": "supporting",
        "primary_function": "methodological_justification",
        "claim_nature": "descriptive",
        "supported_by": [],
        "supports_claims": [],
        "implicit_assumptions": [],
        "location": {
            "section": "2.2. Variables",
            "page": 4,
            "start_paragraph": 5,
            "end_paragraph": 5
        },
        "verbatim_quote": "Our measure collapsed the impact of licit and illicit, intentional and inadvertent activities, including damage from infrastructure construction, aggressive ploughing, or looting.",
        "extraction_confidence": "high"
    }
]

print(f"  Adding {len(new_claims)} new claims (C031-C047)")

print("Extracting implicit arguments from methodology claims...")

# New IMPLICIT ARGUMENTS (IA007-IA008)
new_implicit_arguments = [
    {
        "implicit_id": "IA007",
        "implicit_text": "Field researchers' intuitions and observational beliefs constitute valid basis for initial hypothesis formulation",
        "type": "methodological_assumption",
        "connects_evidence": [],
        "enables_claim": ["C032", "C033"],
        "reasoning": "The paper characterizes hypothesis selection based on researchers' field intuitions as 'perceptive' initial risk assessment, implying this is methodologically appropriate, but does not justify why researcher intuition is adequate basis",
        "verbatim_quote": None,
        "trigger_text": [
            "Researchers in the ﬁeld (including the authors) believed that looting, agricultural activity, and peri-urban development were the principal factors contributing to the ubiquitous degradation",
            "Choosing these factors over others constituted a 'perceptive' initial risk assessment"
        ],
        "trigger_locations": [
            {
                "section": "2. Methodology",
                "subsection": None,
                "start_paragraph": 1,
                "end_paragraph": 1
            }
        ],
        "inference_reasoning": "The characterization of factor selection as 'perceptive' assessment based on researchers' beliefs implies this approach is methodologically sound. However, no justification is provided for why field intuition should be privileged over other methods of factor selection (e.g., literature review, systematic pilot study, stakeholder consultation).",
        "extraction_confidence": "medium",
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        }
    },
    {
        "implicit_id": "IA008",
        "implicit_text": "Large mounds typically contain richer burials than small mounds",
        "type": "disciplinary_assumption",
        "connects_evidence": [],
        "enables_claim": ["C037"],
        "reasoning": "Hypothesis 3 premise that looters target large mounds because they 'typically contain richer burials' is stated as established fact without citation or empirical support in this section",
        "verbatim_quote": None,
        "trigger_text": [
            "looters would preferentially target larger mounds, since they typically contain richer burials than small ones"
        ],
        "trigger_locations": [
            {
                "section": "2. Methodology",
                "subsection": None,
                "start_paragraph": 1,
                "end_paragraph": 1
            }
        ],
        "inference_reasoning": "The causal chain (large mounds → richer burials → preferential looting) depends on the premise that large mounds contain richer burials. This is stated as 'typical' fact without empirical evidence or citation, suggesting it is assumed as disciplinary common knowledge rather than demonstrated for this dataset.",
        "extraction_confidence": "high",
        "location": {
            "section": "2. Methodology",
            "page": 3,
            "start_paragraph": 1,
            "end_paragraph": 1
        }
    }
]

print(f"  Adding {len(new_implicit_arguments)} new implicit arguments (IA007-IA008)")

# Append new items to existing arrays
data["evidence"].extend(new_evidence)
data["claims"].extend(new_claims)
data["implicit_arguments"].extend(new_implicit_arguments)

# Update extraction notes
data["extraction_notes"]["sections_extracted"].append(
    "Pass 1 section 2: Methodology chunk 1 (sections 2, 2.1, 2.2, pages 2-5)"
)

# Update timestamp
data["extraction_timestamp"] = datetime.now(timezone.utc).isoformat()

# Save updated extraction
with open(extraction_file, 'w') as f:
    json.dump(data, f, indent=2)

print(f"\n✓ Section 2 extraction complete")
print(f"  - {len(new_evidence)} new evidence items (E011-E021)")
print(f"  - {len(new_claims)} new claims (C031-C047)")
print(f"  - {len(new_implicit_arguments)} new implicit arguments (IA007-IA008)")
print(f"✓ Updated extraction.json")
