#!/usr/bin/env python3
"""
Pass 1: Liberal Claims & Evidence Extraction
Section 5: Iliad Evidence Part 2 - Book 4.433-38 & Mackie's Analysis
Pages 305-307, ~1100 words

Extracts claims, evidence, and implicit arguments from the analysis of
Iliad 4.433-38 and discussion of Mackie's interpretation.
"""

import json
from datetime import datetime, timezone
from pathlib import Path

extraction_file = Path("extraction.json")

print("=" * 80)
print("PASS 1 - SECTION 5: Iliad Evidence Part 2")
print("Pages 305-307: Book 4.433-38 & Mackie's Analysis")
print("=" * 80)
print()

# Read current extraction data
with open(extraction_file) as f:
    data = json.load(f)

# Section 5 extraction: Iliad 4.433-38 and Mackie's interpretation
section_claims = [
    {
        "id": "C102",
        "content": "Language is only mentioned once in the Catalogues of Iliad 2, where Homer delineates and describes the opposing forces",
        "claim_type": "textual_observation",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "Notably, language is only mentioned once in the Catalogues of Iliad 2, in which Homer delineates and describes the opposing forces",
        "supporting_evidence": [],
        "related_implicit_arguments": ["IA013"]
    },
    {
        "id": "C103",
        "content": "Even in the Catalogues, language is of relatively minor importance, marked by a single adjective before the poet returns to more commonly invoked criteria of identity (military contingent and place of origin)",
        "claim_type": "interpretive_claim",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "Even here it is of relatively minor importance, marked by a single adjective, before the poet returns to more commonly invoked and salient criteria of identity... membership in a military contingent and place of origin",
        "supporting_evidence": [],
        "related_implicit_arguments": ["IA013"]
    },
    {
        "id": "C104",
        "content": "The near-total absence of language from the Catalogues keeps in perspective the role of language in the formation of identity",
        "claim_type": "interpretive_claim",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "The near-total absence of language from the Catalogues keeps in perspective the role of language in the formation of identity",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C105",
        "content": "The heterogeneous speech of the Trojan epikouroi emerges most strongly in Book 4 of the Iliad",
        "claim_type": "textual_observation",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "The heterogeneous speech of the Trojan ἐπίκουροι emerges most strongly in Book 4 of the Iliad",
        "supporting_evidence": ["E005"],
        "related_implicit_arguments": []
    },
    {
        "id": "C106",
        "content": "Homer describes the clamour generated by the Trojan charge with a simile comparing their army to a herd of bleating ewes",
        "claim_type": "textual_observation",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "Homer describes the clamor generated by the Trojan charge with a simile comparing their army to a herd of bleating ewes",
        "supporting_evidence": ["E005"],
        "related_implicit_arguments": []
    },
    {
        "id": "C107",
        "content": "Three words (throos, gērus, and glōssa) used for language in two separate clauses invoke the discord of the Trojan battle cry",
        "claim_type": "textual_observation",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "Three words, θρόος, γῆρυς, and γλῶσσα, used for language in two separate clauses, invoke the discord of the scene",
        "supporting_evidence": ["E005"],
        "related_implicit_arguments": []
    },
    {
        "id": "C108",
        "content": "The languages spoken among the epikouroi are diverse, numerous, and mutually unintelligible (when considered in the context of Iliad 2.802-6)",
        "claim_type": "interpretive_claim",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "emphasizing the fact that the languages spoken among the ἐπίκουροι are diverse, numerous, and—when considered in the context of Iliad 2.802–6, where interpreters prove necessary—mutually unintelligible",
        "supporting_evidence": ["E003", "E005"],
        "related_implicit_arguments": []
    },
    {
        "id": "C109",
        "content": "Language in Iliad 4.438 is subordinate to polis and military divisions, with linguistic variation depending upon place of origin",
        "claim_type": "interpretive_claim",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Furthermore, just as language is subordinate to πόλις and military divisions in Iliad 2.802–6, linguistic variation here depends upon place of origin: γλῶσσα μέμικτο (\"their tongue was mingled\") because they were πολύκλητοι (\"summoned from many lands\")",
        "supporting_evidence": ["E005"],
        "related_implicit_arguments": []
    },
    {
        "id": "C110",
        "content": "Language follows the contours of other aspects of identity, particularly geographic origin",
        "claim_type": "interpretive_claim",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Again, language follows the contours of other aspects of identity, particularly geographic origin",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C111",
        "content": "Mackie uses the presence of linguistic diversity among the Trojan Allies and its absence among the Akhaians as a marker of a broader contrast between Akhaian order and Trojan disorder",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Mackie is one of the few authors to examine linguistic diversity in Homer in detail, using its presence among the Trojan Allies and absence among the Akhaians as a marker of a broader contrast between Akhaian order and Trojan disorder",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C112",
        "content": "When the Trojans march out at the beginning of Book 3, they are still dominated by undifferentiated clamour (klangē)",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "When the Trojans march out at the beginning of Book 3, they are still dominated by undifferentiated clamor (klaggê)",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C113",
        "content": "With their mixed languages, the Trojans cannot function as an articulate group",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "With their mixed languages, the Trojans cannot function as an articulate group",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C114",
        "content": "Because Greek is their common language, the units of the Achaean army form an organic whole, a kosmos 'ordering' of tribes and phratries",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Because Greek is their common language, the units of the Achaean army form an organic whole, a kosmos 'ordering' of tribes and phratries",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C115",
        "content": "The Akhaian unity of language versus the Trojan-allied disunity is a contrast between Trojan clamour and chaos on the one hand and Akhaian cohesion and order on the other",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "In this context, the Akhaian unity of language, versus the Trojan-allied disunity, is a contrast between Trojan clamor and chaos on the one hand and Akhaian cohesion and order on the other",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C116",
        "content": "The speeches made by Akhaian and Trojan heroes differ with respect to diction, theme, purpose, and length",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "The speeches made by Akhaian and Trojan heroes, for example, differ with respect to diction, theme, purpose, and length",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C117",
        "content": "Akhaian speeches tend towards the aggressive; they are public and political, often casting blame",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Akhaian speeches tend towards the aggressive; they are public and political, often casting blame",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C118",
        "content": "Trojan speeches are introspective, private, poetic, and prefer praise over censure",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Trojan speeches, conversely, are introspective, private, poetic, and prefer praise over censure",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C119",
        "content": "The contrast between Trojan and Akhaian speech exposes friction within Archaic Greek society, between the household and political community",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "This contrast between Trojan and Akhaian speech, Mackie continues, exposes friction within Archaic Greek society, between the household and political community, for example",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C120",
        "content": "These tensions are resolved by the Akhaians, who successfully forge a cohesive community, but not by the Trojans, who fail to build such a community with and among their allies",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Mackie believes that these tensions are resolved by the Akhaians, who successfully forge a cohesive community, but not by the Trojans, who fail to build such a community with and among their allies",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C121",
        "content": "The linguistic unity of the Akhaians is one sign of their success at community building; the babble and clamour of the Trojans a mark of their failure",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Taken in this light, the linguistic unity of the Akhaians is one sign of their success at community building; the babble and clamor of the Trojans a mark of their failure",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C122",
        "content": "Mackie views differences between Trojans and Akhaians in the Iliad as an imagined, artistic version of ethnic and cultural difference that does not reflect any real differences between Greek and non-Greek in the eighth century",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Mackie is wary of extending her analysis beyond the context of the poem: \"What we are dealing with is an imagined, artistic version of ethnic and cultural difference\"",
        "supporting_evidence": [],
        "related_implicit_arguments": ["IA014"]
    },
    {
        "id": "C123",
        "content": "For Mackie, differences between Trojans and Akhaians are used to explore features internal to the society that produced the poems, such as tensions between household and political community",
        "claim_type": "scholarly_interpretation",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "For Mackie, differences between Trojans and Akhaians in the Iliad do not reflect any real differences between Greek and non-Greek in the eighth century, but instead are used, at most, to explore features internal to the society that produced the poems",
        "supporting_evidence": [],
        "related_implicit_arguments": ["IA014"]
    },
    {
        "id": "C124",
        "content": "Mackie may be overly cautious in avoiding extension of her analysis beyond the context of the poem",
        "claim_type": "critical_assessment",
        "claim_status": "explicit",
        "page": 306,
        "verbatim_quote": "Mackie may, however, be overly cautious in this regard",
        "supporting_evidence": [],
        "related_implicit_arguments": ["IA015"]
    },
    {
        "id": "C125",
        "content": "Considering the instability in oral traditions of abstractions such as group identity, the unity of the Akhaians in the Iliad would have been more effective as a literary device if it resonated with a genuine sense of Panhellenism emerging among poet and audience in the eighth century BCE",
        "claim_type": "interpretive_claim",
        "claim_status": "explicit",
        "page": 307,
        "verbatim_quote": "Considering the instability in oral traditions of abstractions such as group identity, the unity of the Akhaians in the Iliad would have been more effective as a literary device if it resonated with a genuine sense of Panhellenism emerging among poet and audience in the eighth century b.c.e.",
        "supporting_evidence": [],
        "related_implicit_arguments": ["IA015"]
    },
    {
        "id": "C126",
        "content": "The sheep simile is not limited to the Trojans or intrinsically derogatory; in Iliad 2, the Akhaians are also compared to groups of animals",
        "claim_type": "textual_observation",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "The sheep simile is not limited to the Trojans or intrinsically derogatory; in Il. 2, the Akhaians are also compared to groups of animals",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C127",
        "content": "The poet develops no dichotomy between Akhaians and non-Akhaians along the lines of speaking versus bleating, human versus animal",
        "claim_type": "textual_observation",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "The poet develops no dichotomy between Akhaians and non-Akhaians along the lines of speaking versus bleating, human versus animal",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    },
    {
        "id": "C128",
        "content": "The emphasis in the animal similes is on uniformity versus diversity, Akhaian order versus non-Akhaian chaos",
        "claim_type": "interpretive_claim",
        "claim_status": "explicit",
        "page": 305,
        "verbatim_quote": "Instead, emphasis is on uniformity versus diversity, Akhaian order versus non-Akhaian chaos",
        "supporting_evidence": [],
        "related_implicit_arguments": []
    }
]

section_evidence = [
    {
        "id": "E005",
        "content": "Iliad 4.433-38: The Trojan battle cry described as cacophonous bleating, with no shared speech or voice, their tongue mingled, as they were men summoned from many lands",
        "evidence_type": "primary_source",
        "page": 305,
        "verbatim_quote": "οὐ γὰρ πάντων ἦεν ὁμὸς θρόος οὐδ᾽ ἴα γῆρυς, / ἀλλὰ γλῶσσα μέμικτο, πολύκλητοι δ᾽ ἔσαν ἄνδρες.",
        "source": "Homer, Iliad 4.433-38",
        "related_claims": ["C105", "C106", "C107", "C108", "C109"]
    }
]

section_implicit_arguments = [
    {
        "id": "IA013",
        "content": "The relative importance of identity markers in the Iliad can be gauged by their frequency of mention",
        "claim_type": "methodological_assumption",
        "page": 305,
        "trigger_text": "language is only mentioned once... Even here it is of relatively minor importance... before the poet returns to more commonly invoked and salient criteria",
        "inference_reasoning": "Ross uses frequency of mention as a proxy for salience/importance in Homeric identity construction. This is a methodological assumption about how to read the text—that what is mentioned more often matters more. The contrast between 'only mentioned once' (language) and 'more commonly invoked' (polis/military contingent) implies a hierarchy of identity markers based on textual frequency.",
        "related_claims": ["C102", "C103", "C104"]
    },
    {
        "id": "IA014",
        "content": "Literary/artistic representations can be purely internal explorations of societal tensions without reflecting external ethnic/cultural realities",
        "claim_type": "interpretive_framework",
        "page": 306,
        "trigger_text": "imagined, artistic version of ethnic and cultural difference... do not reflect any real differences... but instead are used... to explore features internal to the society",
        "inference_reasoning": "Mackie's position (as presented by Ross) assumes a strict separation between artistic representation and historical reality. This interpretive framework treats the Trojan-Akhaian contrast as a purely internal Greek discourse rather than reflecting actual encounters with non-Greeks. This is a theoretical position about how literature relates to society—that it can be entirely self-referential.",
        "related_claims": ["C122", "C123"]
    },
    {
        "id": "IA015",
        "content": "Effective literary devices in oral tradition must resonate with audience beliefs and experiences to function successfully",
        "claim_type": "oral_tradition_theory",
        "page": 306,
        "trigger_text": "would have been more effective as a literary device if it resonated with a genuine sense of Panhellenism emerging among poet and audience",
        "inference_reasoning": "Ross's critique of Mackie rests on an unstated theory about how oral tradition works—that literary devices must have some grounding in audience experience/belief to be effective. This builds on Ross's earlier discussion of oral tradition theory but applies it specifically to the relationship between literary representation and historical reality. The assumption is that purely invented contrasts would not resonate effectively.",
        "related_claims": ["C124", "C125"]
    }
]

# Add new items to extraction data
print(f"Adding {len(section_claims)} claims from Section 5...")
data['claims'].extend(section_claims)

print(f"Adding {len(section_evidence)} evidence items from Section 5...")
data['evidence'].extend(section_evidence)

print(f"Adding {len(section_implicit_arguments)} implicit arguments from Section 5...")
data['implicit_arguments'].extend(section_implicit_arguments)

# Update timestamp
data['extraction_timestamp'] = datetime.now(timezone.utc).isoformat()

# Write updated data
with open(extraction_file, 'w') as f:
    json.dump(data, f, indent=2)

print()
print("=" * 80)
print("PASS 1 - SECTION 5 COMPLETE")
print("=" * 80)
print()
print(f"Section 5: Iliad Evidence Part 2 (pp. 305-307)")
print(f"  Claims: {len(section_claims)}")
print(f"  Evidence: {len(section_evidence)}")
print(f"  Implicit Arguments: {len(section_implicit_arguments)}")
print(f"  Total items: {len(section_claims) + len(section_evidence) + len(section_implicit_arguments)}")
print()
print(f"Running total: {len(data['claims'])} claims, {len(data['evidence'])} evidence, {len(data['implicit_arguments'])} implicit_arguments")
print("=" * 80)
