#!/usr/bin/env python3
"""Build hybrid-scorer copies of the nine benchmark arms: rule F2, model elsewhere.

**Version:** 1.0

Validation step (B) of ``wiki/planning/deterministic-output-checks.md``:
the gates validated the model, not the hybrid, so both gate statistics are
recomputed for the hybrid scorer (amendment 3 running-list item 6(b)). This
script makes the hybrid inputs; the registered analysis tool and the H13
script then compute the statistics from them unchanged.

For every committed payload of the nine arms (5 papers x 3 runs each):

* where the F2 rule's status is ``mechanical-0``, the payload's
  ``F2.present`` becomes the rule's value (the governing value under the
  disagreement policy, item 2); ``confirm-1`` and ``no-structured-input``
  leave the model's score in place (none occurs on the pilots);
* each section ``total`` is recomputed as the item sum (policy item 1:
  derived fields are computed, never taken from the model).

Nothing else changes. Outputs go to ``arms/`` beside this script, which is
git-ignored: the copies are regenerated byte for byte from the committed
payloads and ``f2-rule-results.json``, and ``hybrid-build.json`` records the
sha256 of every input and output payload plus every substitution, so a
regeneration can be checked against the record.

Usage (from the repository root):
    venv/bin/python studies/open-science-compliance/outputs/validation/\\
f2-rule-hybrid-2026-10-04/build-hybrid-arms.py
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path
from typing import Any

BUILD_VERSION = "1.0"
HERE = Path(__file__).resolve().parent
VALIDATION_DIR = HERE.parent
REPO_ROOT = VALIDATION_DIR.parents[3]
RULE_RESULTS = HERE / "f2-rule-results.json"
OUT_ROOT = HERE / "arms"

#: The nine committed arms, named explicitly (no globbing), as in H13.
ARMS: dict[str, Path] = {
    "sonnet-5": VALIDATION_DIR / "benchmark-2026-08-17/arm-sonnet-5",
    "opus-5": VALIDATION_DIR / "benchmark-2026-08-17/arm-opus-5",
    "fable-5": VALIDATION_DIR / "benchmark-2026-08-17/arm-fable-5",
    "sonnet-5-high": VALIDATION_DIR / "effort-study-2026-08-17/arm-sonnet-5-high",
    "sonnet-5-max": VALIDATION_DIR / "effort-study-2026-08-17/arm-sonnet-5-max",
    "opus-5-high": VALIDATION_DIR / "effort-study-2026-08-17/arm-opus-5-high",
    "opus-5-5-high": VALIDATION_DIR / "opus-5-5-arms-2026-10/arm-opus-5-5-high",
    "opus-5-5-medium": VALIDATION_DIR / "opus-5-5-arms-2026-10/arm-opus-5-5-medium",
    "opus-5-5-xhigh": VALIDATION_DIR / "opus-5-5-arms-2026-10/arm-opus-5-5-xhigh",
}
RUNS = (1, 2, 3)
SLUGS = ("crema-et-al-2024", "dye-et-al-2023", "herskind-riede-2024",
         "key-et-al-2024", "marwick-2025")
SECTIONS = ("data_fair", "code_fair")


def sha256_bytes(data: bytes) -> str:
    """Return the sha256 hex digest of some bytes."""
    return hashlib.sha256(data).hexdigest()


def rel(path: Path) -> str:
    """Repository-relative path string for the build record."""
    return str(path.resolve().relative_to(REPO_ROOT))


def load_rule() -> dict[tuple[str, str], dict[str, Any]]:
    """Index the F2 rule results by (paper, section)."""
    report = json.loads(RULE_RESULTS.read_text(encoding="utf-8"))
    return {(r["paper"], r["artefact"]): r for r in report["results"]}


def build() -> dict[str, Any]:
    """Write every hybrid payload and return the build record."""
    rule = load_rule()
    record: dict[str, Any] = {
        "generated_by": f"build-hybrid-arms.py v{BUILD_VERSION}",
        "f2_rule_results": rel(RULE_RESULTS),
        "f2_rule_results_sha256": sha256_bytes(RULE_RESULTS.read_bytes()),
        "arms": {},
    }
    for label, arm_dir in ARMS.items():
        out_arm = OUT_ROOT / f"arm-{label}"
        arm_record: dict[str, Any] = {"source": rel(arm_dir), "payloads": [],
                                      "f2_substitutions": [], "total_corrections": []}
        for run in RUNS:
            for slug in SLUGS:
                source = arm_dir / f"run-{run}" / f"{slug}.json"
                raw = source.read_bytes()
                payload = json.loads(raw)
                for section in SECTIONS:
                    block = payload[section]
                    item = block["sub_principles"]["F2"]
                    result = rule[(slug, section)]
                    if result["status"] == "mechanical-0":
                        model_value = int(item["present"])
                        item["present"] = result["rule_value"]
                        if model_value != result["rule_value"]:
                            arm_record["f2_substitutions"].append(
                                {"run": run, "paper": slug, "section": section,
                                 "model": model_value, "rule": result["rule_value"]})
                    computed = sum(int(v["present"]) for v in block["sub_principles"].values())
                    if block.get("total") != computed:
                        # Only a model miscount, not a substituted F2, is a
                        # correction worth reporting: totals always move with F2.
                        model_items = sum(int(v["present"]) for k, v in
                                          json.loads(raw)[section]["sub_principles"].items())
                        if block.get("total") != model_items:
                            arm_record["total_corrections"].append(
                                {"run": run, "paper": slug, "section": section,
                                 "model_total": block.get("total"),
                                 "model_item_sum": model_items})
                        block["total"] = computed
                target = out_arm / f"run-{run}" / f"{slug}.json"
                target.parent.mkdir(parents=True, exist_ok=True)
                out_bytes = (json.dumps(payload, indent=2, ensure_ascii=False) + "\n").encode()
                target.write_bytes(out_bytes)
                arm_record["payloads"].append(
                    {"run": run, "paper": slug, "source_sha256": sha256_bytes(raw),
                     "hybrid_sha256": sha256_bytes(out_bytes)})
        # A minimal run record: the analysis tool reads only "stability", and
        # a hybrid has no published figure to cross-check against.
        (out_arm / "run-record.json").write_text(json.dumps(
            {"arm": label, "hybrid_of": rel(arm_dir),
             "note": "hybrid scorer (rule F2, model elsewhere); no published stability"},
            indent=2) + "\n", encoding="utf-8")
        record["arms"][label] = arm_record
    return record


def main() -> int:
    """Build the hybrid arms and write ``hybrid-build.json``."""
    record = build()
    (HERE / "hybrid-build.json").write_text(
        json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    for label, arm in record["arms"].items():
        print(f"{label:<16} F2 substitutions {len(arm['f2_substitutions']):>2}  "
              f"model total miscounts corrected {len(arm['total_corrections'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
